Fix ArborizeModelTypeHandler
dbbs-lab/bsb-neuron pull request #11
Opened 2024-05-08 08:15 UTC by filimarc

Now  ArborizeModelTypeHandler  __inv__ method return correctly for standard inv_values. For ModelDefinition cases they are converted back to dict.

2024-05-08 09:24 UTC, drodarie requested changes
Could you please add some tests for this function? 
Also since this fix depends on the latest changes in arborize,  I believe you need to update the version required?

2024-05-20 09:20 UTC, Helveg requested changes

2024-05-20 09:20 UTC, Helveg commented on bsb_neuron/cell.py
> +            return str(inv_value)
```suggestion
            return inv_value
```

2024-05-20 09:20 UTC, Helveg commented on tests/test_models.py
> +        assert isinstance(reverse_model, str)
This should test that the config can be reverted to a tree, and parsed again into a config object, and the model properties are maintained:


```
cfg = Configuration(arb_model={"x": 15})
tree = cfg.__tree__()
new_cfg = Configuration(tree)
self.assertEqual(new_cfg.arb_model.x, 15)
```

2024-05-21 12:52 UTC, drodarie requested changes

2024-05-21 12:52 UTC, drodarie commented on bsb_neuron/cell.py
> +            return inv_value
```suggestion

```

2024-05-21 13:56 UTC, merged

2024-05-21 14:10 UTC, Helveg commented
@filimarc was this finally reviewed and approved?